name: mambagym
channels:
  - default
  - pytorch
  - conda-forge
  - nvidia
  - astra-toolbox/label/dev
dependencies:
  - pip
  - numpy=1.24
  - python>=3.8.13
  - pytorch==2.2.0 
  - torchvision==0.17.0 
  - torchaudio==2.2.0 
  - pytorch-cuda=12.1
  - pillow
  - matplotlib
  - scipy
  - astra-toolbox
  - pip:
    - https://github.com/jleuschn/dival.git@master
